# game_other/feature_toggle.py
# Toggle features on/off for development or release builds

ALLOW_HIDDEN_INFO_PANEL = 1
ALLOW_RESOURCE_PANEL = 1
ALLOW_ALERTS_PANEL = 1
ALLOW_INFO_PANEL = 0
ALLOW_PROJECT_OVERVIEW_PANEL = 1
ALLOW_CONSTRUCTION_PANEL = 1
ALLOW_SAVE_AND_LOAD = 0